log:
  level: "info"

runner:
  file: "C:\\actions-runner\\.runner"
  capacity: 1
  timeout: "3h"
  insecure: false
  fetch_interval: "2s"
  labels:
    - "windows:host"
    - "windows-msbuild:host"
    - "windows-latest:host"
    - "windows-2022:host"
    - "windows-node:host"
    - "windows-dotnet:host"

cache:
  enabled: true
  dir: "C:\\tmp\\cache"

host:
  workdir_parent: "C:\\tmp\\act"
